import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms for using Synapse Adaptive.",
};

const UPDATED = "September 6, 2026";
const CONTACT = "support@synapseadaptive.com";

export default function TermsPage() {
  return (
    <main id="main" className="mx-auto max-w-3xl px-5 py-16 sm:py-20">
      <Link href="/" className="text-sm text-muted transition-colors hover:text-ink">← Back to home</Link>
      <h1 className="mt-6 text-3xl font-semibold tracking-tight text-ink sm:text-4xl">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted">Last updated {UPDATED}</p>

      <div className="mt-8 space-y-8 text-[15px] leading-relaxed text-muted">
        <section>
          <p>These terms govern your use of Synapse Adaptive (&ldquo;Synapse&rdquo;). By creating an account or using the app, you agree to them. If you don&apos;t agree, please don&apos;t use Synapse.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">What Synapse is</h2>
          <p className="mt-3">Synapse is a personal-productivity and reflection companion. It offers guidance, accountability, and support to help you follow through on goals. It is a tool to support your own decisions — it is <b className="text-ink">not</b> a provider of medical, mental-health, legal, or financial advice, and it is not a substitute for a qualified professional. In an emergency, contact your local emergency services.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">Your account</h2>
          <p className="mt-3">You&apos;re responsible for keeping your login credentials secure and for activity under your account. You must be old enough to form a binding contract in your jurisdiction (and at least 13). Provide accurate information when you sign up.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">Acceptable use</h2>
          <p className="mt-3">Don&apos;t misuse Synapse: no unlawful activity, no attempts to break, overload, or reverse-engineer the service, no scraping or automated abuse of the AI endpoints, and nothing that infringes others&apos; rights. We may suspend accounts that violate these terms or put the service at risk.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">Your content</h2>
          <p className="mt-3">You own what you put into Synapse. You grant us the limited permission needed to store and process it to operate the service for you (including sending it to our AI provider to generate responses). We don&apos;t claim ownership of your goals, notes, or messages.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">AI-generated content</h2>
          <p className="mt-3">Responses are generated by AI and may be inaccurate or incomplete. Use judgment before acting on them, especially for important decisions. You&apos;re responsible for how you use Synapse&apos;s suggestions.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">Plans &amp; payment</h2>
          <p className="mt-3">Synapse offers a free tier and paid subscriptions. Paid plans are billed through Stripe on a recurring basis until cancelled; you can cancel anytime and access continues through the current billing period. Prices are shown in the app and may change with notice.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">Availability &amp; changes</h2>
          <p className="mt-3">We&apos;re an early product and improve constantly. We may add, change, or remove features, and occasionally the service may be unavailable. We&apos;ll try to avoid disruption but can&apos;t guarantee uninterrupted access.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">Disclaimers &amp; liability</h2>
          <p className="mt-3">Synapse is provided &ldquo;as is,&rdquo; without warranties of any kind. To the fullest extent permitted by law, we aren&apos;t liable for indirect or consequential damages, and our total liability is limited to the amount you paid us in the twelve months before the claim.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">Termination</h2>
          <p className="mt-3">You can stop using Synapse and delete your account at any time. We may suspend or end access if these terms are violated.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-ink">Contact</h2>
          <p className="mt-3">Questions about these terms? Email <a href={`mailto:${CONTACT}`} className="text-orange-400 hover:underline">{CONTACT}</a>.</p>
        </section>

        <p className="border-t pt-6 text-sm">See also our <Link href="/privacy" className="text-orange-400 hover:underline">Privacy Policy</Link>.</p>
      </div>
    </main>
  );
}
